### ISSUE TITLE
error C2220: warning treated as error - no 'object' file generated

### ISSUE THREAD

**Issue by chowdarynamala** [BelledonneCommunications/belcard#1]
Hi All,

I am getting the following error when trying to compile linphone for windows. I see the same issue in other module source files as well. I see in the code an option '/WX' is being added for MSVC which tells compiler to treat warnings as errors, but I am trying to resolve the actual issue that is causing this problem. Could anyone please help me in resolving this?

I am trying to compile with VS2017 and with msvc compiler 19

**c:\users\lakshminarayanac\sources\linphone-desktop\submodules\belcard\tester\belcard-tester.hpp(61): error C2220: warning treated as error - no 'object' file generated [C:\Users\lakshminarayanac\Sources\linphone-desktop\WORK\desktop\Build\belcard\tester\belcard_tester.vcxproj]
c:\users\lakshminarayanac\sources\linphone-desktop\submodules\belcard\tester\belcard-tester.hpp(61): error C2220: warning treated as error - no 'object' file generated [C:\Users\lakshminarayanac\Sources\linphone-desktop\WORK\desktop\Build\belcard\tester\belcard_tester.vcxproj]**

Thanks
Lakshmi

**Comment by chowdarynamala** [comment]
This issue is resolved by updating to the latest belcard submodule.

**Comment by chowdarynamala** [comment]
I still see the same issue after checkout the latest commit

**Comment by KyronNextLevel** [comment]
Hi, if someone still encounter the same issue, please do not build with the support of unit tests. They are not well supported on Windows.
